import type { Execution, AgentInfo, Finding, OrchestraState } from './types';
import { AGENTS, WORKFLOWS } from './constants';

const NOW = new Date();
const minutesAgo = (m: number) => new Date(NOW.getTime() - m * 60000).toISOString();
const hoursAgo = (h: number) => new Date(NOW.getTime() - h * 3600000).toISOString();

// --- Executions ---

export const mockExecutions: Execution[] = [
  {
    id: 'exec-001',
    workflow: 'full-pipeline',
    task: 'Implement user authentication with JWT tokens',
    status: 'running',
    model: 'opus',
    target: 'src/auth/',
    projectSource: { type: 'local', path: '/home/user/projects/my-app' },
    resolvedProjectPath: '/home/user/projects/my-app',
    createdAt: minutesAgo(25),
    startedAt: minutesAgo(24),
    completedAt: null,
    pipeline: [
      {
        phase: 'plan',
        status: 'completed',
        agentRole: 'developer',
        startedAt: minutesAgo(24),
        completedAt: minutesAgo(21),
        output: [
          'Analyzed authentication requirements',
          'Identified 4 components: JWT service, auth middleware, login endpoint, token refresh',
          'Estimated complexity: medium-high',
          'No conflicting modules detected — safe for single-agent execution',
        ],
      },
      {
        phase: 'develop',
        status: 'completed',
        agentRole: 'developer',
        startedAt: minutesAgo(21),
        completedAt: minutesAgo(10),
        output: [
          'Created src/auth/jwt.ts — JWT signing and verification service',
          'Created src/auth/middleware.ts — Express authentication middleware',
          'Created src/auth/login.ts — Login endpoint with credential validation',
          'Created src/auth/refresh.ts — Token refresh endpoint',
          'Updated src/routes/index.ts — Registered auth routes',
          'Fixed 3 TypeScript errors in jwt.ts',
        ],
      },
      {
        phase: 'test',
        status: 'running',
        agentRole: 'tester',
        startedAt: minutesAgo(8),
        completedAt: null,
        output: [
          'Writing unit tests for JWT service...',
          'Writing integration tests for auth middleware...',
          '12 tests passed, 2 failing — investigating',
        ],
      },
      {
        phase: 'security',
        status: 'pending',
        agentRole: null,
        startedAt: null,
        completedAt: null,
        output: [],
      },
      {
        phase: 'report',
        status: 'pending',
        agentRole: null,
        startedAt: null,
        completedAt: null,
        output: [],
      },
    ],
    activities: [
      {
        id: 'act-001',
        agentRole: 'developer',
        action: 'Planning authentication implementation',
        output: [
          '$ find src/ -name "*.ts" | grep -i auth',
          'No existing auth modules found.',
          'Planning new module structure:',
          '  src/auth/jwt.ts',
          '  src/auth/middleware.ts',
          '  src/auth/login.ts',
          '  src/auth/refresh.ts',
        ],
        filesModified: [],
        startedAt: minutesAgo(24),
        completedAt: minutesAgo(21),
        status: 'completed',
      },
      {
        id: 'act-002',
        agentRole: 'developer',
        action: 'Implementing JWT authentication service',
        output: [
          '$ npx tsc --noEmit',
          'src/auth/jwt.ts(45,12): error TS2345: Argument of type \'string\' is not assignable to parameter of type \'SignOptions\'.',
          'src/auth/jwt.ts(52,8): error TS2339: Property \'verify\' does not exist on type \'typeof import("jsonwebtoken")\'.',
          'src/auth/middleware.ts(18,22): error TS7006: Parameter \'decoded\' implicitly has an \'any\' type.',
          'Found 3 errors. Fixing...',
          '$ npx tsc --noEmit',
          'No errors found.',
        ],
        filesModified: [
          'src/auth/jwt.ts',
          'src/auth/middleware.ts',
          'src/auth/login.ts',
          'src/auth/refresh.ts',
          'src/routes/index.ts',
        ],
        startedAt: minutesAgo(21),
        completedAt: minutesAgo(10),
        status: 'completed',
      },
      {
        id: 'act-003',
        agentRole: 'tester',
        action: 'Running test suite for auth module',
        output: [
          '$ npx vitest run src/auth/',
          '',
          ' PASS  src/auth/__tests__/jwt.test.ts',
          '   JWT Service',
          '     - signs tokens with correct payload (4ms)',
          '     - verifies valid tokens (2ms)',
          '     - rejects expired tokens (3ms)',
          '     - rejects tampered tokens (1ms)',
          '',
          ' FAIL  src/auth/__tests__/middleware.test.ts',
          '   Auth Middleware',
          '     - allows requests with valid token (3ms)',
          '     x rejects requests without token (5ms)',
          '       Expected: 401',
          '       Received: 500',
          '     x rejects requests with expired token (2ms)',
          '       Expected: 401',
          '       Received: 500',
          '',
          ' PASS  src/auth/__tests__/login.test.ts',
          '   Login Endpoint',
          '     - returns token for valid credentials (8ms)',
          '     - returns 401 for invalid password (3ms)',
          '     - returns 404 for unknown user (2ms)',
          '',
          ' Tests: 2 failed, 10 passed, 12 total',
          ' Investigating middleware error handling...',
        ],
        filesModified: [
          'src/auth/__tests__/jwt.test.ts',
          'src/auth/__tests__/middleware.test.ts',
          'src/auth/__tests__/login.test.ts',
        ],
        startedAt: minutesAgo(8),
        completedAt: null,
        status: 'running',
      },
    ],
    findings: ['finding-005', 'finding-007', 'finding-010'],
  },
  {
    id: 'exec-002',
    workflow: 'code-review',
    task: 'Review PR #47: Add rate limiting to API endpoints',
    status: 'completed',
    model: 'sonnet',
    target: 'src/middleware/rateLimit.ts',
    createdAt: hoursAgo(2),
    startedAt: hoursAgo(2),
    completedAt: minutesAgo(112),
    pipeline: [
      {
        phase: 'plan',
        status: 'completed',
        agentRole: 'developer',
        startedAt: hoursAgo(2),
        completedAt: minutesAgo(118),
        output: ['Reviewing PR #47 scope and changes', 'Identified 3 files changed, 142 lines added'],
      },
      {
        phase: 'develop',
        status: 'completed',
        agentRole: 'developer',
        startedAt: minutesAgo(118),
        completedAt: minutesAgo(115),
        output: [
          'Code structure is clean and follows existing patterns',
          'Rate limiting uses sliding window algorithm — good choice',
          'Suggestion: Extract magic numbers into config constants',
        ],
      },
      {
        phase: 'test',
        status: 'completed',
        agentRole: 'tester',
        startedAt: minutesAgo(118),
        completedAt: minutesAgo(114),
        output: [
          'Test coverage for rateLimit.ts: 87%',
          'Missing edge case: concurrent requests from same IP',
          'All 8 existing tests pass',
        ],
      },
      {
        phase: 'security',
        status: 'completed',
        agentRole: 'devsecops',
        startedAt: minutesAgo(118),
        completedAt: minutesAgo(113),
        output: [
          'Rate limiting implementation is sound',
          'Found: Missing rate limit on auth endpoint (HIGH)',
          'Found: No IP-based blocking for brute force attempts',
          'Recommendation: Add progressive delays after 5 failed attempts',
        ],
      },
      {
        phase: 'report',
        status: 'completed',
        agentRole: 'developer',
        startedAt: minutesAgo(113),
        completedAt: minutesAgo(112),
        output: [
          'RECOMMENDATION: REQUEST CHANGES',
          '- Add rate limiting to /auth/login endpoint',
          '- Add test for concurrent requests edge case',
          '- Extract rate limit config values to constants',
        ],
      },
    ],
    activities: [
      {
        id: 'act-004',
        agentRole: 'developer',
        action: 'Reviewing code quality and architecture',
        output: [
          '$ git diff main...feature/rate-limiting -- src/middleware/rateLimit.ts',
          '+export function createRateLimiter(options: RateLimitOptions) {',
          '+  const windowMs = options.windowMs || 60000;',
          '+  const maxRequests = options.max || 100;',
          '...',
          'Review: Clean implementation. Follows middleware pattern.',
        ],
        filesModified: [],
        startedAt: minutesAgo(118),
        completedAt: minutesAgo(115),
        status: 'completed',
      },
      {
        id: 'act-005',
        agentRole: 'tester',
        action: 'Running test coverage analysis',
        output: [
          '$ npx vitest run --coverage src/middleware/',
          ' PASS  src/middleware/__tests__/rateLimit.test.ts (8 tests)',
          'Coverage: 87% statements, 82% branches',
          'Uncovered: lines 45-52 (concurrent window cleanup)',
        ],
        filesModified: [],
        startedAt: minutesAgo(118),
        completedAt: minutesAgo(114),
        status: 'completed',
      },
      {
        id: 'act-006',
        agentRole: 'devsecops',
        action: 'Security review of rate limiting',
        output: [
          '$ grep -rn "rateLimit" src/routes/',
          'src/routes/api.ts:12: app.use("/api", rateLimiter);',
          'src/routes/auth.ts: — NO rate limiting found',
          'FINDING: /auth/login endpoint has no rate limiting',
          'SEVERITY: HIGH — enables brute force attacks',
        ],
        filesModified: [],
        startedAt: minutesAgo(118),
        completedAt: minutesAgo(113),
        status: 'completed',
      },
    ],
    findings: ['finding-003', 'finding-006', 'finding-008'],
  },
  {
    id: 'exec-003',
    workflow: 'security-audit',
    task: 'Security audit of payment processing module',
    status: 'failed',
    model: 'opus',
    target: 'src/payments/',
    createdAt: hoursAgo(5),
    startedAt: hoursAgo(5),
    completedAt: hoursAgo(4),
    pipeline: [
      {
        phase: 'plan',
        status: 'completed',
        agentRole: 'devsecops',
        startedAt: hoursAgo(5),
        completedAt: minutesAgo(295),
        output: [
          'Scoping security audit for payment processing module',
          'Files in scope: 12 TypeScript files, 3 config files',
          'Focus areas: input validation, encryption, secret management, PCI compliance',
        ],
      },
      {
        phase: 'security',
        status: 'failed',
        agentRole: 'devsecops',
        startedAt: minutesAgo(295),
        completedAt: hoursAgo(4),
        output: [
          'CRITICAL: SQL injection vulnerability in src/payments/query.ts:34',
          'CRITICAL: Hardcoded Stripe API key in src/payments/config.ts:8',
          'HIGH: Insecure direct object reference in order lookup',
          'MEDIUM: Sensitive payment data stored unencrypted in localStorage',
          'Audit FAILED — 2 critical findings require immediate remediation',
        ],
      },
      {
        phase: 'report',
        status: 'completed',
        agentRole: 'devsecops',
        startedAt: hoursAgo(4),
        completedAt: minutesAgo(238),
        output: [
          'SECURITY AUDIT RESULT: FAIL',
          '2 Critical, 1 High, 2 Medium findings',
          'Immediate action required: Remove hardcoded API key, fix SQL injection',
          'Full remediation plan attached to findings',
        ],
      },
    ],
    activities: [
      {
        id: 'act-007',
        agentRole: 'devsecops',
        action: 'Scanning for secrets and vulnerabilities',
        output: [
          '$ grep -rn "sk_live\\|sk_test\\|api_key\\|secret" src/payments/',
          'src/payments/config.ts:8: const STRIPE_KEY = "sk_live_51abc...xyz";',
          'CRITICAL: Hardcoded Stripe live API key detected!',
          '',
          '$ grep -rn "query\\|exec\\|raw" src/payments/',
          'src/payments/query.ts:34: const result = db.query(`SELECT * FROM orders WHERE id = ${orderId}`);',
          'CRITICAL: Unsanitized user input in SQL query — SQL injection vector',
        ],
        filesModified: [],
        startedAt: minutesAgo(295),
        completedAt: hoursAgo(4),
        status: 'completed',
      },
    ],
    findings: ['finding-001', 'finding-002', 'finding-004', 'finding-009'],
  },
  {
    id: 'exec-004',
    workflow: 'full-pipeline',
    task: 'Refactor database connection pooling for better performance',
    status: 'queued',
    model: 'opus',
    target: 'src/db/',
    projectSource: { type: 'new', path: '' },
    resolvedProjectPath: '/home/vscode/orchestra-projects/exec-004',
    createdAt: minutesAgo(3),
    startedAt: null,
    completedAt: null,
    pipeline: [
      {
        phase: 'plan',
        status: 'pending',
        agentRole: null,
        startedAt: null,
        completedAt: null,
        output: [],
      },
      {
        phase: 'develop',
        status: 'pending',
        agentRole: null,
        startedAt: null,
        completedAt: null,
        output: [],
      },
      {
        phase: 'test',
        status: 'pending',
        agentRole: null,
        startedAt: null,
        completedAt: null,
        output: [],
      },
      {
        phase: 'security',
        status: 'pending',
        agentRole: null,
        startedAt: null,
        completedAt: null,
        output: [],
      },
      {
        phase: 'report',
        status: 'pending',
        agentRole: null,
        startedAt: null,
        completedAt: null,
        output: [],
      },
    ],
    activities: [],
    findings: [],
  },
];

// --- Agents ---

export const mockAgents: AgentInfo[] = AGENTS;

// --- Findings ---

export const mockFindings: Finding[] = [
  {
    id: 'finding-001',
    executionId: 'exec-003',
    type: 'security',
    severity: 'critical',
    status: 'open',
    title: 'SQL injection in user input handling',
    description:
      'The payment query function in src/payments/query.ts directly interpolates user-supplied orderId into a SQL query string without sanitization or parameterization. An attacker can inject arbitrary SQL to read, modify, or delete data.',
    file: 'src/payments/query.ts',
    line: 34,
    remediation:
      'Replace string interpolation with parameterized queries. Use db.query("SELECT * FROM orders WHERE id = $1", [orderId]) to prevent SQL injection.',
    agent: 'devsecops',
    createdAt: hoursAgo(4),
  },
  {
    id: 'finding-002',
    executionId: 'exec-003',
    type: 'security',
    severity: 'high',
    status: 'open',
    title: 'Hardcoded API key in configuration file',
    description:
      'A live Stripe API key (sk_live_*) is hardcoded in src/payments/config.ts. This key is committed to version control and visible to anyone with repository access. If leaked, it allows unauthorized charges and access to payment data.',
    file: 'src/payments/config.ts',
    line: 8,
    remediation:
      'Remove the hardcoded key immediately. Rotate the compromised key in the Stripe dashboard. Use environment variables (process.env.STRIPE_SECRET_KEY) with a .env file excluded from version control.',
    agent: 'devsecops',
    createdAt: hoursAgo(4),
  },
  {
    id: 'finding-003',
    executionId: 'exec-002',
    type: 'security',
    severity: 'high',
    status: 'open',
    title: 'Missing rate limiting on authentication endpoint',
    description:
      'The /auth/login endpoint has no rate limiting applied, while other API endpoints are protected. This allows unlimited login attempts, enabling brute force and credential stuffing attacks.',
    file: 'src/routes/auth.ts',
    line: 15,
    remediation:
      'Apply the existing rateLimiter middleware to the auth routes. Use a stricter limit for login (e.g., 5 attempts per minute) and implement progressive delays after repeated failures.',
    agent: 'devsecops',
    createdAt: hoursAgo(2),
  },
  {
    id: 'finding-004',
    executionId: 'exec-003',
    type: 'security',
    severity: 'medium',
    status: 'open',
    title: 'Insecure direct object reference in order lookup',
    description:
      'The order retrieval endpoint uses sequential numeric IDs without authorization checks. An authenticated user can access any order by incrementing the order ID, exposing other users\' payment information.',
    file: 'src/payments/orders.ts',
    line: 22,
    remediation:
      'Add authorization middleware to verify the requesting user owns the order. Use UUIDs instead of sequential IDs to make enumeration harder. Implement row-level security checks.',
    agent: 'devsecops',
    createdAt: hoursAgo(4),
  },
  {
    id: 'finding-005',
    executionId: 'exec-001',
    type: 'security',
    severity: 'medium',
    status: 'open',
    title: 'Missing CSRF protection on authentication forms',
    description:
      'The login and token refresh endpoints do not validate CSRF tokens. An attacker could craft a malicious page that submits authentication requests on behalf of a logged-in user, potentially stealing session tokens.',
    file: 'src/auth/login.ts',
    line: 28,
    remediation:
      'Implement CSRF token validation using the double-submit cookie pattern or synchronizer token pattern. Add a CSRF middleware that generates and validates tokens for all state-changing requests.',
    agent: 'devsecops',
    createdAt: minutesAgo(15),
  },
  {
    id: 'finding-006',
    executionId: 'exec-002',
    type: 'quality',
    severity: 'low',
    status: 'resolved',
    title: 'Console.log statements left in production code',
    description:
      'Multiple console.log statements used for debugging were left in the rate limiting middleware. These create noise in production logs and may inadvertently expose request data.',
    file: 'src/middleware/rateLimit.ts',
    line: 23,
    remediation:
      'Remove all console.log statements or replace with a structured logging library (e.g., winston, pino) that supports log levels and can be configured per environment.',
    agent: 'tester',
    createdAt: hoursAgo(2),
  },
  {
    id: 'finding-007',
    executionId: 'exec-001',
    type: 'quality',
    severity: 'low',
    status: 'open',
    title: 'Missing input validation on email field',
    description:
      'The login endpoint accepts any string as an email address without validation. While this doesn\'t directly cause a security issue, it can lead to confusing error messages and unnecessary database lookups.',
    file: 'src/auth/login.ts',
    line: 12,
    remediation:
      'Add email format validation using a regex pattern or a validation library like zod. Return a 400 Bad Request with a clear error message for invalid email formats.',
    agent: 'tester',
    createdAt: minutesAgo(8),
  },
  {
    id: 'finding-008',
    executionId: 'exec-002',
    type: 'compliance',
    severity: 'info',
    status: 'dismissed',
    title: 'Deprecated dependency detected: express-rate-limit@5.x',
    description:
      'The project uses express-rate-limit version 5.x which has been deprecated in favor of version 7.x. While the current version has no known vulnerabilities, it will not receive future security patches.',
    file: 'package.json',
    line: null,
    remediation:
      'Upgrade to express-rate-limit@7.x. Review the migration guide for breaking changes, particularly the new configuration options and store interface changes.',
    agent: 'devsecops',
    createdAt: hoursAgo(2),
  },
  {
    id: 'finding-009',
    executionId: 'exec-003',
    type: 'security',
    severity: 'medium',
    status: 'open',
    title: 'Unencrypted sensitive data in localStorage',
    description:
      'Payment-related data including partial card numbers and transaction IDs are stored in the browser\'s localStorage without encryption. This data persists across sessions and is accessible to any JavaScript running on the same origin.',
    file: 'src/payments/store.ts',
    line: 15,
    remediation:
      'Remove sensitive payment data from localStorage entirely. If client-side caching is required, use sessionStorage with encrypted values and implement automatic cleanup. Consider using httpOnly cookies for sensitive tokens.',
    agent: 'devsecops',
    createdAt: hoursAgo(4),
  },
  {
    id: 'finding-010',
    executionId: 'exec-001',
    type: 'compliance',
    severity: 'info',
    status: 'open',
    title: 'Missing Content-Security-Policy header',
    description:
      'The application does not set a Content-Security-Policy (CSP) header. Without CSP, the application is more vulnerable to XSS attacks as browsers cannot restrict which resources are loaded and executed.',
    file: 'src/auth/middleware.ts',
    line: null,
    remediation:
      'Add a Content-Security-Policy header to all responses. Start with a restrictive policy (default-src \'self\') and gradually allow required external resources. Use report-uri to monitor violations before enforcing.',
    agent: 'devsecops',
    createdAt: minutesAgo(15),
  },
];

// --- Workflows ---

export const mockWorkflows = WORKFLOWS;

// --- Combined State ---

export const mockState: OrchestraState = {
  executions: mockExecutions,
  agents: mockAgents,
  findings: mockFindings,
  workflows: mockWorkflows,
  authStatus: null,
  isLive: false,
};
